[project]
name = "glaciation-uc4-shoalmate"
version = "0.1.0"
description = "Multi-cluster data orchestrator for GLACIATION use case 4"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
