[project]
name = "glaciation-uc4-shoalmate"
version = "0.1.0"
description = "Multi-cluster data orchestrator for GLACIATION use case 4"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "minio>=7.2.15",
    "parquet>=1.3.1",
    "pydantic-settings>=2.9.1",
]

[project.optional-dependencies]
dev = ["mypy>=1.8.0", "pytest>=8.0.0"]

[tool.mypy]
python_version = "3.13"
strict = true
