apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoalmate
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: shoalmate
  template:
    metadata:
      labels:
        app: shoalmate
    spec:
      containers:
        - name: analyser
          image: "ghcr.io/glaciation-heu/shoalmate:{{ .Chart.AppVersion }}"
          resources:
            requests:
              cpu: {{ .Values.analyser.resources.requests.cpu }}
              memory: {{ .Values.analyser.resources.requests.memory }}
            limits:
              cpu: {{ .Values.analyser.resources.limits.cpu }}
              memory: {{ .Values.analyser.resources.limits.memory }}