apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoalmate
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: shoalmate
  template:
    metadata:
      labels:
        app: shoalmate
    spec:
      containers:
        - name: shoalmate
          image: "ghcr.io/glaciation-heu/shoalmate:{{ .Chart.AppVersion }}"
          command: ["python", "-m", "shoalmate.main"]
          resources:
            requests:
              cpu: {{ .Values.shoalmate.resources.requests.cpu }}
              memory: {{ .Values.shoalmate.resources.requests.memory }}
            limits:
              cpu: {{ .Values.shoalmate.resources.limits.cpu }}
              memory: {{ .Values.shoalmate.resources.limits.memory }}
          envFrom:
            - secretRef:
                name: {{ .Values.shoalmate.secretName }}
