apiVersion: apps/v1
kind: Deployment
metadata:
  name: timesim
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: timesim
  template:
    metadata:
      labels:
        app: timesim
    spec:
      containers:
        - name: shoalmate
          image: "ghcr.io/glaciation-heu/shoalmate:{{ .Chart.AppVersion }}"
          command: ["fastapi", "run", "timesim/main.py"]
          ports:
            - containerPort: 8000
              name: http
          resources:
            requests:
              cpu: {{ .Values.timesim.resources.requests.cpu }}
              memory: {{ .Values.timesim.resources.requests.memory }}
            limits:
              cpu: {{ .Values.timesim.resources.limits.cpu }}
              memory: {{ .Values.timesim.resources.limits.memory }}
