apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shoalmate
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingressHostName }}
      http:
        paths:
          - backend:
              service:
                name: timesim
                port:
                  number: 80
            path: /
            pathType: Prefix
